#!/bin/sh
# Tcl ignores the next line -*- tcl -*- \
exec wish "$0" -- "$@"

# This is an implementation of a simple yes no dialog
# which is injected into the git commandline by git gui
# in case a yesno question needs to be answered.
#
# The window title, which defaults to "Question?", can be
# overridden via the optional `--title` command-line
# option.

set title "Question?"
if {$argc < 1} {
	puts stderr "Usage: $argv0 <question>"
	exit 1
} else {
	if {$argc > 2 && [lindex $argv 0] == "--title"} {
		set title [lindex $argv 1]
		set argv [lreplace $argv 0 1]
	}
	set prompt [join $argv " "]
}

set dlgicon {question}
if {$::tcl_platform(platform) eq {windows}} {
	set icopath [file dirname [file normalize $argv0]]
	if {[file tail $icopath] eq {git-core}} {
		set icopath [file dirname $icopath]
	}
	set icopath [file dirname $icopath]
	set icopath [file join $icopath share git git-for-windows.ico]
	if {[file exists $icopath]} {
		set dlgicon $icopath
	}
}

wm withdraw .

option add *Dialog.msg.font {Sans 10}
set ans [tk_messageBox -icon $dlgicon -message $prompt -title $title -type yesno]
exit [expr $ans eq {no}]
